from typing import Dict, List, Set, NamedTuple
from BaseClasses import ItemClassification

class WOLItemData(NamedTuple):
    id_offset: int
    classification: ItemClassification
    categories: Set = {}
    copies_in_pool: int = 1
    is_dlc: bool = False

base_id = 752813602

item_table: Dict[str, WOLItemData] = {
    "Attorney's Badge": WOLItemData(0, ItemClassification.useful, {"Gear", "Lapel"}, is_dlc=True),
    "Bean-Iron Badge": WOLItemData(1, ItemClassification.useful, {"Gear", "Lapel"}),
    "Blood-Soaked Pocket Square": WOLItemData(2, ItemClassification.useful, {"Gear", "Lapel", "Prog Loot"}),
    "Bowling Shirt Nametag": WOLItemData(3, ItemClassification.useful, {"Gear", "Lapel"}, is_dlc=True),
    "Buffalo Bandolier": WOLItemData(4, ItemClassification.useful, {"Gear", "Lapel"}),
    "CGAS Badge": WOLItemData(5, ItemClassification.useful, {"Gear", "Lapel"}, is_dlc=True),
    "Chest Full Of Medals": WOLItemData(6, ItemClassification.useful, {"Gear", "Lapel", "Prog Loot"}),
    "El Vibrato Brooch": WOLItemData(7, ItemClassification.useful, {"Gear", "Lapel", "Prog Loot"}),
    "Enchanted Bandolier": WOLItemData(8, ItemClassification.useful, {"Gear", "Lapel"}),
    "Fine Bandolier": WOLItemData(9, ItemClassification.useful, {"Gear", "Lapel"}),
    "Gilded Lily": WOLItemData(10, ItemClassification.useful, {"Gear", "Lapel"}),
    "Golden Scarab Pin": WOLItemData(11, ItemClassification.useful, {"Gear", "Lapel"}),
    "Gothic Cameo": WOLItemData(12, ItemClassification.useful, {"Gear", "Lapel"}),
    "Greased Bandolier": WOLItemData(13, ItemClassification.useful, {"Gear", "Lapel"}),
    "Halloway's Pin": WOLItemData(14, ItemClassification.progression, {"Gear", "Lapel"}),
    "Lucky Marigold": WOLItemData(15, ItemClassification.useful, {"Gear", "Lapel"}),
    "Medal Of Adequacy": WOLItemData(16, ItemClassification.useful, {"Gear", "Lapel"}),
    "Necromancers, I Hate 'Em Button": WOLItemData(17, ItemClassification.useful, {"Gear", "Lapel"}),
    "Perfumed Pocket Square": WOLItemData(18, ItemClassification.useful, {"Gear", "Lapel", "Prog Loot"}),
    "Purple Brain Pin": WOLItemData(19, ItemClassification.useful, {"Gear", "Lapel"}),
    "Reinforced Pocket Square": WOLItemData(20, ItemClassification.useful, {"Gear", "Lapel", "Prog Loot"}),
    "Replica Sherf Badge": WOLItemData(21, ItemClassification.useful, {"Gear", "Lapel"}),
    "Revolting Brooch": WOLItemData(22, ItemClassification.useful, {"Gear", "Lapel"}),
    "Rifleman Insignia Pin": WOLItemData(23, ItemClassification.useful, {"Gear", "Lapel"}),
    "Rusty Deputy Badge": WOLItemData(24, ItemClassification.useful, {"Gear", "Lapel"}),
    "Shimmering Pocket Square": WOLItemData(25, ItemClassification.useful, {"Gear", "Lapel", "Prog Loot"}),
    "Shiny Abalone Brooch": WOLItemData(26, ItemClassification.useful, {"Gear", "Lapel"}),
    "Smiling Face Button": WOLItemData(27, ItemClassification.useful, {"Gear", "Lapel"}),
    "Smoking Crysanthemum": WOLItemData(28, ItemClassification.useful, {"Gear", "Lapel"}),
    "Stylish Pocket Square": WOLItemData(29, ItemClassification.useful, {"Gear", "Lapel", "Prog Loot"}),
    "Tentacled Badge": WOLItemData(30, ItemClassification.useful, {"Gear", "Lapel"}),
    "Texas Ranger Badge": WOLItemData(31, ItemClassification.useful, {"Gear", "Lapel"}),
    "Weirdly Deformed Bone": WOLItemData(32, ItemClassification.useful, {"Gear", "Lapel"}),
    "3 Ball": WOLItemData(33, ItemClassification.useful, {"Gear", "Offhand"}, is_dlc=True),
    "5 Ball": WOLItemData(34, ItemClassification.useful, {"Gear", "Offhand"}, is_dlc=True),
    "6-Ball": WOLItemData(35, ItemClassification.useful, {"Gear", "Offhand"}, is_dlc=True),
    "Ancient Bean Can": WOLItemData(36, ItemClassification.useful, {"Gear", "Offhand"}),
    "Antique Rangefinder": WOLItemData(37, ItemClassification.useful, {"Gear", "Offhand"}),
    "Bean-Iron Kettle": WOLItemData(38, ItemClassification.useful, {"Gear", "Offhand"}),
    "Bean-Iron Saucepan": WOLItemData(39, ItemClassification.useful, {"Gear", "Offhand"}),
    "Bean-Iron Skillet": WOLItemData(40, ItemClassification.useful, {"Gear", "Offhand"}),
    "Br*** Censer": WOLItemData(41, ItemClassification.useful, {"Gear", "Offhand"}),
    "Breadwood Cheat Sheet": WOLItemData(42, ItemClassification.useful, {"Gear", "Offhand"}),
    "Caged Canary": WOLItemData(43, ItemClassification.useful, {"Gear", "Offhand", "Prog Loot"}),
    "Can Of Infinite Beans": WOLItemData(44, ItemClassification.useful, {"Gear", "Offhand"}),
    "Dramatic Goblin Skull": WOLItemData(45, ItemClassification.useful, {"Gear", "Offhand"}),
    "Driftwood Sculpture": WOLItemData(46, ItemClassification.useful, {"Gear", "Offhand"}),
    "El Vibrato Cone": WOLItemData(47, ItemClassification.useful, {"Gear", "Offhand", "Prog Loot"}),
    "Filthy Porcelain Cone": WOLItemData(48, ItemClassification.useful, {"Gear", "Offhand"}),
    "Ghost Flower": WOLItemData(49, ItemClassification.useful, {"Gear", "Offhand"}),
    "Glass Sphere": WOLItemData(50, ItemClassification.useful, {"Gear", "Offhand"}),
    "Goblin Spyglass": WOLItemData(51, ItemClassification.useful, {"Gear", "Offhand"}),
    "Goblin Trash Sack": WOLItemData(52, ItemClassification.useful, {"Gear", "Offhand"}),
    "Gun Manor Pistol Token": WOLItemData(53, ItemClassification.useful, {"Gear", "Offhand"}, is_dlc=True),
    "Gun Manor Rifle Token": WOLItemData(54, ItemClassification.useful, {"Gear", "Offhand"}, is_dlc=True),
    "Gun Manor Shotgun Token": WOLItemData(55, ItemClassification.useful, {"Gear", "Offhand"}, is_dlc=True),
    "Infernal Leather Bag": WOLItemData(56, ItemClassification.useful, {"Gear", "Offhand"}),
    "Large Plush Bear": WOLItemData(57, ItemClassification.useful, {"Gear", "Offhand"}),
    "Large Plush Cat": WOLItemData(58, ItemClassification.useful, {"Gear", "Offhand"}),
    "Large Plush Owl": WOLItemData(59, ItemClassification.useful, {"Gear", "Offhand"}),
    "Lucky Horseshoe": WOLItemData(60, ItemClassification.useful, {"Gear", "Offhand"}),
    "Macready's Pocketwatch": WOLItemData(61, ItemClassification.progression, {"Gear", "Offhand"}, is_dlc=True),
    "Rucker's Ranchsack": WOLItemData(62, ItemClassification.useful, {"Gear", "Offhand", "Prog Loot"}),
    "Sea Skull": WOLItemData(63, ItemClassification.useful, {"Gear", "Offhand"}),
    "Shiny Ball": WOLItemData(64, ItemClassification.useful, {"Gear", "Offhand"}),
    "Small Plush Bear": WOLItemData(65, ItemClassification.useful, {"Gear", "Offhand"}),
    "Small Plush Kitten": WOLItemData(66, ItemClassification.useful, {"Gear", "Offhand"}),
    "Small Plush Owl": WOLItemData(67, ItemClassification.useful, {"Gear", "Offhand"}),
    "Smoldering Leather Bag": WOLItemData(68, ItemClassification.useful, {"Gear", "Offhand"}),
    "Souvenir Spoon": WOLItemData(69, ItemClassification.useful, {"Gear", "Offhand"}),
    "Stove Door": WOLItemData(70, ItemClassification.useful, {"Gear", "Offhand"}),
    "Strange Glass Rectangle": WOLItemData(71, ItemClassification.useful, {"Gear", "Offhand"}),
    "Sweet-Smellin' Flowers": WOLItemData(72, ItemClassification.useful, {"Gear", "Offhand"}),
    "The Hedge Wizard's Orb": WOLItemData(73, ItemClassification.progression, {"Gear", "Offhand"}, is_dlc=True),
    "Thick Leather Bag": WOLItemData(74, ItemClassification.useful, {"Gear", "Offhand"}),
    "Vibrating Scapula": WOLItemData(75, ItemClassification.useful, {"Gear", "Offhand"}),
    "Weird Silver Idol": WOLItemData(76, ItemClassification.useful, {"Gear", "Offhand"}),
    "Worry Stone": WOLItemData(77, ItemClassification.useful, {"Gear", "Offhand"}),
    "Barnaby Bob's Burnished Boots": WOLItemData(78, ItemClassification.useful, {"Gear", "Boots"}),
    "Big Furry Boots": WOLItemData(79, ItemClassification.useful, {"Gear", "Boots"}),
    "Black Boots": WOLItemData(80, ItemClassification.useful, {"Gear", "Boots"}),
    "Boost Boots": WOLItemData(81, ItemClassification.useful, {"Gear", "Boots"}),
    "Brown Boots": WOLItemData(82, ItemClassification.useful, {"Gear", "Boots"}),
    "El Vibrato Boots": WOLItemData(83, ItemClassification.useful, {"Gear", "Boots", "Prog Loot"}),
    "Extra-Large Boots": WOLItemData(84, ItemClassification.useful, {"Gear", "Boots"}),
    "Flashy Boots": WOLItemData(85, ItemClassification.useful, {"Gear", "Boots"}),
    "Hide Shoes": WOLItemData(86, ItemClassification.useful, {"Gear", "Boots"}),
    "Hightailin' Boots": WOLItemData(87, ItemClassification.useful, {"Gear", "Boots"}),
    "Infernal Leather Boots": WOLItemData(88, ItemClassification.useful, {"Gear", "Boots"}),
    "Jackboots": WOLItemData(89, ItemClassification.useful, {"Gear", "Boots"}),
    "Old Spanish Sabatons": WOLItemData(90, ItemClassification.useful, {"Gear", "Boots"}),
    "Orthopedic Boots": WOLItemData(91, ItemClassification.useful, {"Gear", "Boots", "Prog Loot"}),
    "Overly-Tanned Boots": WOLItemData(92, ItemClassification.useful, {"Gear", "Boots"}),
    "Riding Boots": WOLItemData(93, ItemClassification.useful, {"Gear", "Boots"}),
    "Running Boots": WOLItemData(94, ItemClassification.useful, {"Gear", "Boots"}),
    "Silk Nun's Boots": WOLItemData(95, ItemClassification.useful, {"Gear", "Boots"}),
    "Smoldering Leather Boots": WOLItemData(96, ItemClassification.useful, {"Gear", "Boots"}),
    "Spit-Soaked Boots": WOLItemData(97, ItemClassification.useful, {"Gear", "Boots"}),
    "Thick Leather Boots": WOLItemData(98, ItemClassification.useful, {"Gear", "Boots"}),
    "Tony's Bear-Soaked Boots": WOLItemData(99, ItemClassification.useful, {"Gear", "Boots"}),
    "Tony's Enchanted Boots": WOLItemData(100, ItemClassification.useful, {"Gear", "Boots"}),
    "Tony's Inscribed Boots": WOLItemData(101, ItemClassification.useful, {"Gear", "Boots"}),
    "Tony's Meaty Boots": WOLItemData(102, ItemClassification.useful, {"Gear", "Boots"}),
    "Tony's Shiny Boots": WOLItemData(103, ItemClassification.useful, {"Gear", "Boots"}),
    "Tony's Shootin' Boots": WOLItemData(104, ItemClassification.useful, {"Gear", "Boots"}),
    "Tony's Thick-Soled Boots": WOLItemData(105, ItemClassification.useful, {"Gear", "Boots"}),
    "Tony's Tiger-Striped Boots": WOLItemData(106, ItemClassification.useful, {"Gear", "Boots"}),
    "Wet Boots": WOLItemData(107, ItemClassification.useful, {"Gear", "Boots"}),
    "Work Boots": WOLItemData(108, ItemClassification.useful, {"Gear", "Boots"}),
    "Arcane Geode Hat": WOLItemData(109, ItemClassification.useful, {"Gear", "Hats"}),
    "Barely-Enchanted Hat": WOLItemData(110, ItemClassification.useful, {"Gear", "Hats"}),
    "Battered Old Top Hat": WOLItemData(111, ItemClassification.useful, {"Gear", "Hats"}),
    "Bean-Iron Collander": WOLItemData(112, ItemClassification.useful, {"Gear", "Hats"}),
    "Bear Hat": WOLItemData(113, ItemClassification.useful, {"Gear", "Hats"}),
    "Black Hood": WOLItemData(114, ItemClassification.useful, {"Gear", "Hats"}),
    "Bowling Ball Hat": WOLItemData(115, ItemClassification.useful, {"Gear", "Hats"}, is_dlc=True),
    "Burning Tophat": WOLItemData(116, ItemClassification.useful, {"Gear", "Hats"}),
    "Cat Hat": WOLItemData(117, ItemClassification.useful, {"Gear", "Hats"}),
    "Colorful Hat": WOLItemData(118, ItemClassification.useful, {"Gear", "Hats"}),
    "Cowboy Chef's Hat": WOLItemData(119, ItemClassification.useful, {"Gear", "Hats"}),
    "Crackerjack Hat": WOLItemData(120, ItemClassification.useful, {"Gear", "Hats"}),
    "Crazy Electric Helmet": WOLItemData(121, ItemClassification.useful, {"Gear", "Hats"}),
    "Cultist Leader Mask": WOLItemData(122, ItemClassification.useful, {"Gear", "Hats"}),
    "Cultist Mask": WOLItemData(123, ItemClassification.useful, {"Gear", "Hats"}),
    "Dilapidated Old Wizard Hat": WOLItemData(124, ItemClassification.useful, {"Gear", "Hats"}),
    "Driftwood Sculpture": WOLItemData(125, ItemClassification.useful, {"Gear", "Hats"}),
    "El Vibrato Crown": WOLItemData(126, ItemClassification.progression, {"Gear", "Hats"}),
    "El Vibrato Headband": WOLItemData(127, ItemClassification.progression, {"Gear", "Hats"}),
    "El Vibrato Helmet": WOLItemData(128, ItemClassification.useful, {"Gear", "Hats", "Prog Loot"}),
    "Ellsbury's Helmet": WOLItemData(129, ItemClassification.useful, {"Gear", "Hats"}),
    "Enchanted Buffalo Skull": WOLItemData(130, ItemClassification.useful, {"Gear", "Hats"}),
    "Extra-Black Hat": WOLItemData(131, ItemClassification.useful, {"Gear", "Hats"}),
    "Fake Pope Hat": WOLItemData(132, ItemClassification.useful, {"Gear", "Hats"}),
    "Floppy Derby": WOLItemData(133, ItemClassification.useful, {"Gear", "Hats"}),
    "Four-Gallon Hat": WOLItemData(134, ItemClassification.useful, {"Gear", "Hats"}),
    "Funerary Derby": WOLItemData(135, ItemClassification.useful, {"Gear", "Hats", "Prog Loot"}),
    "Gasmask": WOLItemData(136, ItemClassification.useful, {"Gear", "Hats"}),
    "General Gob's Hat": WOLItemData(137, ItemClassification.useful, {"Gear", "Hats"}),
    "Ghost Cowboy Hat": WOLItemData(138, ItemClassification.useful, {"Gear", "Hats"}),
    "Ghost Skin Cap": WOLItemData(139, ItemClassification.useful, {"Gear", "Hats"}),
    "Goblin Tiara": WOLItemData(140, ItemClassification.useful, {"Gear", "Hats"}),
    "Gold Tooth Crown": WOLItemData(141, ItemClassification.progression, {"Gear", "Hats"}),
    "Gold Tooth Tiara": WOLItemData(142, ItemClassification.useful, {"Gear", "Hats"}),
    "Infernal Leather Hat": WOLItemData(143, ItemClassification.useful, {"Gear", "Hats"}),
    "Kurtzfit Headband": WOLItemData(144, ItemClassification.progression, {"Gear", "Hats"}),
    "Marmotskin Cap": WOLItemData(145, ItemClassification.useful, {"Gear", "Hats"}),
    "Miner's Helmet": WOLItemData(146, ItemClassification.useful, {"Gear", "Hats"}),
    "Old Cavalry Hat": WOLItemData(147, ItemClassification.useful, {"Gear", "Hats"}),
    "Old Patrol Cap": WOLItemData(148, ItemClassification.progression, {"Gear", "Hats"}),
    "Owl Hat": WOLItemData(149, ItemClassification.useful, {"Gear", "Hats"}),
    "Prototype Stetson": WOLItemData(150, ItemClassification.useful, {"Gear", "Hats"}),
    "Really Nice Cowboy Hat": WOLItemData(151, ItemClassification.useful, {"Gear", "Hats"}),
    "Rifleman's Helmet": WOLItemData(152, ItemClassification.useful, {"Gear", "Hats"}),
    "Rusty Old Viking Helmet": WOLItemData(153, ItemClassification.useful, {"Gear", "Hats"}),
    "Sloppy Chef's Hat": WOLItemData(154, ItemClassification.useful, {"Gear", "Hats"}),
    "Sloppy Cowboy Hat": WOLItemData(155, ItemClassification.useful, {"Gear", "Hats"}),
    "Sloppy Tophat": WOLItemData(156, ItemClassification.useful, {"Gear", "Hats"}),
    "Smoldering Leather Hat": WOLItemData(157, ItemClassification.useful, {"Gear", "Hats"}),
    "Spittoon Hat": WOLItemData(158, ItemClassification.useful, {"Gear", "Hats"}),
    "Strange Head Sack": WOLItemData(159, ItemClassification.useful, {"Gear", "Hats"}),
    "Stripey Hat": WOLItemData(160, ItemClassification.useful, {"Gear", "Hats"}),
    "Teeny-Tiny Hat": WOLItemData(161, ItemClassification.useful, {"Gear", "Hats"}),
    "The Necromancer's Crown": WOLItemData(162, ItemClassification.progression, {"Gear", "Hats"}),
    "Thick Leather Hat": WOLItemData(163, ItemClassification.useful, {"Gear", "Hats"}),
    "Turnip Crown": WOLItemData(164, ItemClassification.progression, {"Gear", "Hats"}),
    "Wreath Of Laurels": WOLItemData(165, ItemClassification.useful, {"Gear", "Hats"}, is_dlc=True),
    "Yeast-Covered Hat": WOLItemData(166, ItemClassification.useful, {"Gear", "Hats"}),
    "Bean-Stained Pants": WOLItemData(167, ItemClassification.useful, {"Gear", "Pants"}),
    "Bearskin Pants": WOLItemData(168, ItemClassification.useful, {"Gear", "Pants"}),
    "Birthing Breeches": WOLItemData(169, ItemClassification.useful, {"Gear", "Pants", "Prog Loot"}),
    "Black Denim Pants": WOLItemData(170, ItemClassification.useful, {"Gear", "Pants"}),
    "Buffaloskin Pants": WOLItemData(171, ItemClassification.useful, {"Gear", "Pants"}),
    "Cargo Chaps": WOLItemData(172, ItemClassification.useful, {"Gear", "Pants"}),
    "Cargo Jeans": WOLItemData(173, ItemClassification.useful, {"Gear", "Pants"}),
    "Chastity Pants": WOLItemData(174, ItemClassification.useful, {"Gear", "Pants"}),
    "Coffee-Stained Pants": WOLItemData(175, ItemClassification.useful, {"Gear", "Pants"}),
    "Cursed Pants": WOLItemData(176, ItemClassification.useful, {"Gear", "Pants"}),
    "Double-Silk Pantaloons": WOLItemData(177, ItemClassification.useful, {"Gear", "Pants"}, is_dlc=True),
    "Eight-Legged Pants": WOLItemData(178, ItemClassification.useful, {"Gear", "Pants"}, is_dlc=True),
    "El Vibrato Pants": WOLItemData(179, ItemClassification.useful, {"Gear", "Pants"}),
    "Entire Leather Pants": WOLItemData(180, ItemClassification.useful, {"Gear", "Pants"}),
    "Fancy Pantry Pants": WOLItemData(181, ItemClassification.useful, {"Gear", "Pants"}, is_dlc=True),
    "Flexible Chaps": WOLItemData(182, ItemClassification.useful, {"Gear", "Pants"}),
    "Goblin Shortpants": WOLItemData(183, ItemClassification.useful, {"Gear", "Pants"}),
    "Goblin Trousers": WOLItemData(184, ItemClassification.useful, {"Gear", "Pants"}),
    "Infernal Breeches": WOLItemData(185, ItemClassification.useful, {"Gear", "Pants"}),
    "Inflexible Chaps": WOLItemData(186, ItemClassification.useful, {"Gear", "Pants"}),
    "Kitchen Pants": WOLItemData(187, ItemClassification.useful, {"Gear", "Pants"}),
    "Kneeling Pants": WOLItemData(188, ItemClassification.useful, {"Gear", "Pants"}),
    "Kurtzfit Pants": WOLItemData(189, ItemClassification.progression, {"Gear", "Pants"}),
    "Magician's Pants": WOLItemData(190, ItemClassification.useful, {"Gear", "Pants"}),
    "Miner's Pants": WOLItemData(191, ItemClassification.useful, {"Gear", "Pants"}),
    "Old Silk Trousers": WOLItemData(192, ItemClassification.useful, {"Gear", "Pants", "Prog Loot"}),
    "Smoldering Leather Pants": WOLItemData(193, ItemClassification.useful, {"Gear", "Pants"}),
    "Somethingskin Pants": WOLItemData(194, ItemClassification.useful, {"Gear", "Pants"}),
    "Spit-Soaked Pants": WOLItemData(195, ItemClassification.useful, {"Gear", "Pants"}),
    "Thick Chaps": WOLItemData(196, ItemClassification.useful, {"Gear", "Pants"}),
    "Thick Leather Pants": WOLItemData(197, ItemClassification.useful, {"Gear", "Pants"}),
    "Thick Quilted Pants": WOLItemData(198, ItemClassification.useful, {"Gear", "Pants"}),
    "Army-Issue Sidearm": WOLItemData(199, ItemClassification.useful, {"Gear", "Pistols"}),
    "Bandit Pistol": WOLItemData(200, ItemClassification.useful, {"Gear", "Pistols"}),
    "Bandit Revolver": WOLItemData(201, ItemClassification.useful, {"Gear", "Pistols"}),
    "Bean-Iron Shootin' Iron": WOLItemData(202, ItemClassification.useful, {"Gear", "Pistols"}),
    "Befouled Pistol": WOLItemData(203, ItemClassification.useful, {"Gear", "Pistols"}),
    "Cookin' Pistol": WOLItemData(204, ItemClassification.useful, {"Gear", "Pistols"}),
    "Deputy Pistol": WOLItemData(205, ItemClassification.useful, {"Gear", "Pistols"}),
    "Desert Gang's Sixgun": WOLItemData(206, ItemClassification.useful, {"Gear", "Pistols"}),
    "El Vibrato Pistol": WOLItemData(207, ItemClassification.useful, {"Gear", "Pistols", "Prog Loot"}),
    "General Gob's Pistol": WOLItemData(208, ItemClassification.useful, {"Gear", "Pistols"}),
    "Ghost Pistol": WOLItemData(209, ItemClassification.useful, {"Gear", "Pistols"}),
    "Goblin Pistol": WOLItemData(210, ItemClassification.useful, {"Gear", "Pistols"}),
    "Intimidating Sixgun": WOLItemData(211, ItemClassification.useful, {"Gear", "Pistols"}),
    "Medical Gun": WOLItemData(212, ItemClassification.useful, {"Gear", "Pistols", "Prog Loot"}),
    "Mrs. Gun's Opus": WOLItemData(213, ItemClassification.useful, {"Gear", "Pistols"}, is_dlc=True),
    "Muck-Clogged Blunderbuss": WOLItemData(214, ItemClassification.useful, {"Gear", "Pistols"}),
    "New-Fangled Pistol": WOLItemData(215, ItemClassification.useful, {"Gear", "Pistols"}),
    "Rancher's Pistol": WOLItemData(216, ItemClassification.useful, {"Gear", "Pistols", "Prog Loot"}),
    "Red-Hot Pistol": WOLItemData(217, ItemClassification.useful, {"Gear", "Pistols"}),
    "Sigiled Pistol": WOLItemData(218, ItemClassification.useful, {"Gear", "Pistols"}),
    "Silver Pistol": WOLItemData(219, ItemClassification.useful, {"Gear", "Pistols"}),
    "Smoking Gun": WOLItemData(220, ItemClassification.useful, {"Gear", "Pistols"}),
    "The Worst Gun": WOLItemData(221, ItemClassification.useful, {"Gear", "Pistols"}, is_dlc=True),
    "Toilet Pistol": WOLItemData(222, ItemClassification.useful, {"Gear", "Pistols"}),
    "Ancient Ring": WOLItemData(223, ItemClassification.useful, {"Gear", "Rings"}),
    "Bone-Chip Ring": WOLItemData(224, ItemClassification.useful, {"Gear", "Rings"}),
    "Bowling Championship Ring": WOLItemData(225, ItemClassification.useful, {"Gear", "Rings"}, is_dlc=True),
    "Branding Ring": WOLItemData(226, ItemClassification.useful, {"Gear", "Rings", "Prog Loot"}),
    "Coal Ring": WOLItemData(227, ItemClassification.useful, {"Gear", "Rings"}),
    "Coccyx With A Hole In It": WOLItemData(228, ItemClassification.useful, {"Gear", "Rings"}),
    "Cool Sapphire Ring": WOLItemData(229, ItemClassification.useful, {"Gear", "Rings"}),
    "Cow-Catcher Ring": WOLItemData(230, ItemClassification.useful, {"Gear", "Rings"}),
    "Cowseye Ring": WOLItemData(231, ItemClassification.useful, {"Gear", "Rings"}),
    "Effluvious Emerald Ring": WOLItemData(232, ItemClassification.useful, {"Gear", "Rings"}),
    "El Vibrato Ring": WOLItemData(233, ItemClassification.useful, {"Gear", "Rings", "Prog Loot"}),
    "Floral Ring": WOLItemData(234, ItemClassification.useful, {"Gear", "Rings"}),
    "Ghost Ring": WOLItemData(235, ItemClassification.useful, {"Gear", "Rings"}),
    "Glowing Ring": WOLItemData(236, ItemClassification.useful, {"Gear", "Rings"}),
    "Goblin Engagement Ring": WOLItemData(237, ItemClassification.useful, {"Gear", "Rings"}),
    "Goblin Glass Ring": WOLItemData(238, ItemClassification.useful, {"Gear", "Rings"}),
    "Goblin Lead Ring": WOLItemData(239, ItemClassification.useful, {"Gear", "Rings"}),
    "Goblin Nail Ring": WOLItemData(240, ItemClassification.useful, {"Gear", "Rings"}),
    "Huge Diamond Ring": WOLItemData(241, ItemClassification.useful, {"Gear", "Rings"}),
    "Lodestone Ring": WOLItemData(242, ItemClassification.useful, {"Gear", "Rings", "Prog Loot"}),
    "Meat-Stained Ring": WOLItemData(243, ItemClassification.useful, {"Gear", "Rings"}),
    "Military School Class Ring": WOLItemData(244, ItemClassification.useful, {"Gear", "Rings", "Prog Loot"}),
    "Nasty Ring": WOLItemData(245, ItemClassification.useful, {"Gear", "Rings"}),
    "Old Engagement Ring": WOLItemData(246, ItemClassification.filler, {"Gear", "Rings", "Prog Loot"}),
    "Ring Of Gettin' Places Faster": WOLItemData(247, ItemClassification.useful, {"Gear", "Rings"}),
    "Ring Of Inconspicuousness": WOLItemData(248, ItemClassification.useful, {"Gear", "Rings"}),
    "Ring Of Moderate Unpunchability": WOLItemData(249, ItemClassification.useful, {"Gear", "Rings"}),
    "Ring Of Smart Thinkin'": WOLItemData(250, ItemClassification.useful, {"Gear", "Rings"}),
    "Ring Of Strongth": WOLItemData(251, ItemClassification.useful, {"Gear", "Rings"}),
    "Sandalwood Ring": WOLItemData(252, ItemClassification.useful, {"Gear", "Rings"}),
    "Santa Cortada's Ring": WOLItemData(253, ItemClassification.useful, {"Gear", "Rings"}),
    "Serpentine Ring": WOLItemData(254, ItemClassification.useful, {"Gear", "Rings"}),
    "Silicon Ring": WOLItemData(255, ItemClassification.useful, {"Gear", "Rings"}),
    "Special Magic Ring": WOLItemData(256, ItemClassification.useful, {"Gear", "Rings"}),
    "Thaumomoprhic Diorite Ring": WOLItemData(257, ItemClassification.useful, {"Gear", "Rings"}),
    "Unbreakable Ruby Ring": WOLItemData(258, ItemClassification.useful, {"Gear", "Rings"}),
    "Artillery Saber": WOLItemData(259, ItemClassification.useful, {"Gear", "Melee", "Prog Loot"}),
    "Balanced Billiards Cue": WOLItemData(260, ItemClassification.progression, {"Gear", "Melee"}, is_dlc=True),
    "Barry Knife": WOLItemData(261, ItemClassification.useful, {"Gear", "Melee"}),
    "Bean-Iron Ladle": WOLItemData(262, ItemClassification.useful, {"Gear", "Melee"}),
    "Bean-Iron Spatula": WOLItemData(263, ItemClassification.useful, {"Gear", "Melee"}),
    "Bean-Iron Whisk": WOLItemData(264, ItemClassification.useful, {"Gear", "Melee"}),
    "Blechscalibur": WOLItemData(265, ItemClassification.useful, {"Gear", "Melee"}),
    "Bloodied Cleaver": WOLItemData(266, ItemClassification.useful, {"Gear", "Melee"}),
    "Bone Sword": WOLItemData(267, ItemClassification.useful, {"Gear", "Melee"}),
    "Bowling Pin": WOLItemData(268, ItemClassification.useful, {"Gear", "Melee"}, is_dlc=True),
    "Brass Knuckles": WOLItemData(269, ItemClassification.useful, {"Gear", "Melee"}),
    "Broken Board": WOLItemData(270, ItemClassification.useful, {"Gear", "Melee"}),
    "Bush Whacker": WOLItemData(271, ItemClassification.useful, {"Gear", "Melee"}, is_dlc=True),
    "Cactus Club": WOLItemData(272, ItemClassification.useful, {"Gear", "Melee"}),
    "Clown Knife": WOLItemData(273, ItemClassification.useful, {"Gear", "Melee"}),
    "Construction Sledgehammer": WOLItemData(274, ItemClassification.useful, {"Gear", "Melee"}),
    "Crowbar": WOLItemData(275, ItemClassification.progression, {"Gear", "Melee"}),
    "Driftwood Sculpture": WOLItemData(276, ItemClassification.useful, {"Gear", "Melee"}),
    "El Vibrato Club": WOLItemData(277, ItemClassification.useful, {"Gear", "Melee", "Prog Loot"}),
    "Fancy Knife": WOLItemData(278, ItemClassification.useful, {"Gear", "Melee"}),
    "Fang-Gloves": WOLItemData(279, ItemClassification.useful, {"Gear", "Melee"}),
    "Goblin Trashbat": WOLItemData(280, ItemClassification.useful, {"Gear", "Melee"}),
    "Gulch Goblin Axe": WOLItemData(281, ItemClassification.useful, {"Gear", "Melee"}),
    "Gulch Goblin Spatula": WOLItemData(282, ItemClassification.useful, {"Gear", "Melee"}),
    "Hammer": WOLItemData(283, ItemClassification.progression, {"Gear", "Melee"}),
    "Hard Loaf": WOLItemData(284, ItemClassification.useful, {"Gear", "Melee"}),
    "Hedge Clippers": WOLItemData(285, ItemClassification.useful, {"Gear", "Melee"}, is_dlc=True),
    "Infernal Mallet": WOLItemData(286, ItemClassification.progression, {"Gear", "Melee"}),
    "Jumbo Jumbo Shrimp Fork": WOLItemData(287, ItemClassification.useful, {"Gear", "Melee"}, is_dlc=True),
    "Leather Shears": WOLItemData(288, ItemClassification.useful, {"Gear", "Melee"}),
    "Monkey Wrench": WOLItemData(289, ItemClassification.progression, {"Gear", "Melee"}),
    "Mushroom-Covered Bone": WOLItemData(290, ItemClassification.useful, {"Gear", "Melee"}),
    "Nailgoves": WOLItemData(291, ItemClassification.useful, {"Gear", "Melee"}),
    "Old Cavalry Saber": WOLItemData(292, ItemClassification.useful, {"Gear", "Melee"}),
    "Old Pickaxe": WOLItemData(293, ItemClassification.useful, {"Gear", "Melee"}),
    "Pickaxe": WOLItemData(294, ItemClassification.progression, {"Gear", "Melee"}),
    "Plunger": WOLItemData(295, ItemClassification.useful, {"Gear", "Melee"}),
    "Red-Hot Poker": WOLItemData(296, ItemClassification.useful, {"Gear", "Melee"}),
    "Repurposed Cult Dagger": WOLItemData(297, ItemClassification.useful, {"Gear", "Melee"}),
    "Rock Hammer": WOLItemData(298, ItemClassification.useful, {"Gear", "Melee", "Prog Loot"}),
    "Spider Axe": WOLItemData(299, ItemClassification.useful, {"Gear", "Melee"}, is_dlc=True),
    "St. Beefus' Thigh": WOLItemData(300, ItemClassification.useful, {"Gear", "Melee"}),
    "Stainless Steel Bean Pan": WOLItemData(301, ItemClassification.useful, {"Gear", "Melee"}, is_dlc=True),
    "Stuffed Gun": WOLItemData(302, ItemClassification.useful, {"Gear", "Melee"}, is_dlc=True),
    "Sweet Sword": WOLItemData(303, ItemClassification.useful, {"Gear", "Melee"}),
    "The Carver": WOLItemData(304, ItemClassification.useful, {"Gear", "Melee"}, is_dlc=True),
    "Tuna Fork": WOLItemData(305, ItemClassification.useful, {"Gear", "Melee"}),
    "Ungulith-Horn Gloves": WOLItemData(306, ItemClassification.useful, {"Gear", "Melee"}),
    "Varmint Skinnin' Knife": WOLItemData(307, ItemClassification.useful, {"Gear", "Melee"}),
    "Weird Knife": WOLItemData(308, ItemClassification.useful, {"Gear", "Melee"}),
    "Wobbly Billiards Cue": WOLItemData(309, ItemClassification.useful, {"Gear", "Melee"}, is_dlc=True),
    "Kellogg Grain Flakes": WOLItemData(310, ItemClassification.progression, {"Consumables", "Food"}),
    "Cheap Cigar": WOLItemData(311, ItemClassification.progression, {"Consumables", "Potions"}, is_dlc=True),
    "Can Of Kerosene": WOLItemData(312, ItemClassification.progression, {"Consumables", "Combat"}),
    "1878 Nautical Almanac": WOLItemData(313, ItemClassification.progression, {"Books"}, is_dlc=True),
    "Advanced Beancraft": WOLItemData(314, ItemClassification.useful, {"Books"}, 8),
    "Advanced Cow Punchin'": WOLItemData(315, ItemClassification.useful, {"Books"}, 8),
    "Basics Of Gun Law": WOLItemData(316, ItemClassification.progression, {"Books"}, is_dlc=True),
    "Beans Illustrated": WOLItemData(317, ItemClassification.progression, {"Books"}),
    "The Best Love Poem Ever Written": WOLItemData(318, ItemClassification.filler, {"Books"}),
    "Burned Leatherworking Manual": WOLItemData(319, ItemClassification.progression, {"Books"}),
    "Cannon Loading For Idjits": WOLItemData(320, ItemClassification.useful, {"Books"}),
    "Progressive Nex-Mex Skillbook": WOLItemData(321, ItemClassification.progression, {"Books"}, 7),
    "Desert Eatin' And Drinkin'": WOLItemData(323, ItemClassification.progression, {"Books"}),
    "The Diary Of Alexandria Alexandria": WOLItemData(324, ItemClassification.filler, {"Books"}),
    "Duel Law": WOLItemData(325, ItemClassification.progression, {"Books"}, is_dlc=True),
    "Duelling Banjos": WOLItemData(326, ItemClassification.progression, {"Books"}, is_dlc=True),
    "Forgotten Lore": WOLItemData(327, ItemClassification.useful, {"Books"}),
    "Fun Law: Rules For Parlor Games": WOLItemData(329, ItemClassification.progression, {"Books"}, is_dlc=True),
    "Get Crackin': A Guide To Modern Safes": WOLItemData(331, ItemClassification.progression, {"Books"}),
    "Gold Medal Silversmithing": WOLItemData(332, ItemClassification.useful, {"Books"}),
    "Hedging Your Bets": WOLItemData(333, ItemClassification.useful, {"Books"}, is_dlc=True),
    "How To \"Cheat\" At \"Poker\"": WOLItemData(335, ItemClassification.useful, {"Books"}),
    "Kickin' Ass And Chewin' Gum": WOLItemData(338, ItemClassification.useful, {"Books"}),
    "Locks And How To Pick Them": WOLItemData(339, ItemClassification.progression, {"Books"}),
    "Mind Your Meat": WOLItemData(340, ItemClassification.progression, {"Books"}),
    "Modern Snake Oiler": WOLItemData(341, ItemClassification.progression, {"Books"}, 8),
    "Mycology, Yourcology": WOLItemData(342, ItemClassification.progression, {"Books"}),
    "Oils I Have Known": WOLItemData(343, ItemClassification.useful, {"Books"}),
    "Percussive Maintenance": WOLItemData(344, ItemClassification.progression, {"Books"}),
    "The Quick And The Drunk": WOLItemData(345, ItemClassification.useful, {"Books"}),
    "Rich Vein, Poor Vein": WOLItemData(346, ItemClassification.useful, {"Books"}),
    "Tanning And Tanning": WOLItemData(347, ItemClassification.useful, {"Books"}),
    "To Serve Food To Mankind": WOLItemData(348, ItemClassification.useful, {"Books"}),
    "Walking Stupid": WOLItemData(349, ItemClassification.filler, {"Books"}),
    "1.2337\" Diameter Tin Can": WOLItemData(350, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "A Bunch Of Really Small Guns": WOLItemData(351, ItemClassification.progression, {"Quest Items"}),
    "A Pile Of Loose Chili Beans": WOLItemData(352, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "A Year's Supply Of Dynamite": WOLItemData(353, ItemClassification.progression, {"Quest Items"}),
    "Artillery Targeting Flare": WOLItemData(354, ItemClassification.progression, {"Quest Items"}),
    "Attic-Opening Stick": WOLItemData(355, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "Bag Of Grease": WOLItemData(356, ItemClassification.progression, {"Quest Items"}),
    "Bag Of Mixed Grain": WOLItemData(357, ItemClassification.progression, {"Quest Items"}),
    "Bale Of Cowsbane": WOLItemData(358, ItemClassification.progression, {"Quest Items"}),
    "Big Coil Of Barbed Wire": WOLItemData(359, ItemClassification.progression, {"Quest Items"}),
    "Blank Sheet Music": WOLItemData(360, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "Blue Chalk": WOLItemData(361, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "Bottle Of Ghost Whiskey": WOLItemData(362, ItemClassification.progression, {"Quest Items"}),
    "Box Of Science Doohickeys": WOLItemData(363, ItemClassification.useful, {"Quest Items"}, is_dlc=True),
    "Breadwood Bread Bowl x5": WOLItemData(364, ItemClassification.progression, {"Quest Items"}),
    "Breadwood Logging Permit Forms": WOLItemData(365, ItemClassification.progression, {"Quest Items"}),
    "Breadwood Logging Report": WOLItemData(366, ItemClassification.progression, {"Quest Items"}),
    "Breadwood Logging Report Folder": WOLItemData(367, ItemClassification.progression, {"Quest Items"}),
    "Breadwood's Missing Mail": WOLItemData(368, ItemClassification.progression, {"Quest Items"}),
    "Broken Leg Pills": WOLItemData(369, ItemClassification.useful, {"Quest Items"}),
    "Buffalo Pile Locker Key": WOLItemData(370, ItemClassification.progression, {"Quest Items"}),
    "Buffalo Soldier Diagram": WOLItemData(371, ItemClassification.progression, {"Quest Items"}),
    "Burned Scroll": WOLItemData(372, ItemClassification.progression, {"Quest Items"}),
    "Cargo Car Key": WOLItemData(373, ItemClassification.useful, {"Quest Items"}),
    "Charred Locket": WOLItemData(374, ItemClassification.useful, {"Quest Items"}),
    "Child's Bracelet": WOLItemData(375, ItemClassification.useful, {"Quest Items"}),
    "Chili Sin Pistoles": WOLItemData(376, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "Chili Sin Pistoles (Muerto)": WOLItemData(377, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "Chili Spices": WOLItemData(378, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "Chuck's Key": WOLItemData(379, ItemClassification.progression, {"Quest Items"}),
    "Circus Show Ticket": WOLItemData(380, ItemClassification.progression, {"Quest Items"}),
    "Circus Ticket": WOLItemData(381, ItemClassification.progression, {"Quest Items"}),
    "Clip-On Bow Tie": WOLItemData(382, ItemClassification.useful, {"Quest Items"}),
    "Comedy Flier": WOLItemData(383, ItemClassification.useful, {"Quest Items"}),
    "Creepy Whispering Stone": WOLItemData(384, ItemClassification.useful, {"Quest Items"}),
    "Cryptic Note About Ley Lines": WOLItemData(385, ItemClassification.progression, {"Quest Items"}),
    "Curly's Auto-Gyrotheodolite": WOLItemData(386, ItemClassification.progression, {"Quest Items"}),
    "Curly's Compass": WOLItemData(387, ItemClassification.progression, {"Quest Items"}),
    "Curly's Strongbox": WOLItemData(388, ItemClassification.useful, {"Quest Items"}),
    "Dave's Secret Sauce Recipe": WOLItemData(389, ItemClassification.progression, {"Quest Items"}),
    "Demi-Culverin Cannonball": WOLItemData(390, ItemClassification.progression, {"Quest Items"}),
    "Desert Ape Skeleton": WOLItemData(391, ItemClassification.useful, {"Quest Items"}),
    "Dictionary Page (Poach)": WOLItemData(392, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "Dining Car Key": WOLItemData(393, ItemClassification.useful, {"Quest Items"}),
    "Discipline Slip": WOLItemData(394, ItemClassification.progression, {"Quest Items"}),
    "El Vibrato Cross": WOLItemData(395, ItemClassification.progression, {"Quest Items"}),
    "El Vibrato Cylinder": WOLItemData(396, ItemClassification.progression, {"Quest Items"}, 3),
    "El Vibrato Device": WOLItemData(397, ItemClassification.useful, {"Quest Items"}),
    "El Vibrato Model Bridge": WOLItemData(400, ItemClassification.progression, {"Quest Items"}),
    "El Vibrato Rod": WOLItemData(401, ItemClassification.useful, {"Quest Items"}),
    "El Vibrato Transponder": WOLItemData(402, ItemClassification.progression, {"Quest Items"}),
    "Elevator Button": WOLItemData(403, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "Emergency Form Transfer Envelope": WOLItemData(404, ItemClassification.progression, {"Quest Items"}),
    "Fort Treason Ballistics Chart": WOLItemData(405, ItemClassification.progression, {"Quest Items"}),
    "Forty Loaves Of Bread": WOLItemData(406, ItemClassification.progression, {"Quest Items"}),
    "Gas Cap": WOLItemData(407, ItemClassification.progression, {"Quest Items"}),
    "Geometry Textbook": WOLItemData(408, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "Ghost Pencil": WOLItemData(409, ItemClassification.progression, {"Quest Items"}),
    "Ghost Staple Remover": WOLItemData(410, ItemClassification.progression, {"Quest Items"}),
    "Ghost Stapler": WOLItemData(411, ItemClassification.progression, {"Quest Items"}),
    "Ghostwood Visitor's ID": WOLItemData(412, ItemClassification.progression, {"Quest Items"}),
    "Ghostwood Visitor's Permit": WOLItemData(413, ItemClassification.progression, {"Quest Items"}),
    "Glass Eye": WOLItemData(414, ItemClassification.progression, {"Quest Items"}),
    "Goblet Of Blood": WOLItemData(415, ItemClassification.useful, {"Quest Items"}),
    "Gore-Splattered Scroll": WOLItemData(416, ItemClassification.progression, {"Quest Items"}),
    "Green Green Apple Jellybeans": WOLItemData(417, ItemClassification.useful, {"Quest Items"}),
    "Gun Manor Carriage House Key": WOLItemData(418, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "Gun Manor Guest Room Key": WOLItemData(419, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "Gun Manor Photo": WOLItemData(420, ItemClassification.filler, {"Quest Items"}, is_dlc=True),
    "Gustavson Gulch Treasure Cave Key": WOLItemData(421, ItemClassification.progression, {"Quest Items"}),
    "Gustavson Gulch Treasure Cave Key (Spare)": WOLItemData(422, ItemClassification.progression, {"Quest Items"}),
    "Half A Ton Of Yeast": WOLItemData(423, ItemClassification.progression, {"Quest Items"}),
    "High-Tech Drill Bit": WOLItemData(424, ItemClassification.progression, {"Quest Items"}),
    "Honey Jelly Bean": WOLItemData(425, ItemClassification.progression, {"Quest Items"}),
    "Interesting Rock": WOLItemData(426, ItemClassification.progression, {"Quest Items"}),
    "Jumbleneck Mine Elevator Key": WOLItemData(427, ItemClassification.progression, {"Quest Items"}),
    "Kellogg Ranch Keyring": WOLItemData(428, ItemClassification.progression, {"Quest Items"}),
    "Kellogg Ranch Workout Regimen": WOLItemData(429, ItemClassification.filler, {"Quest Items"}),
    "Kellogg's Grain Flakes Recipe": WOLItemData(430, ItemClassification.filler, {"Quest Items"}),
    "Key Fragment 1": WOLItemData(431, ItemClassification.progression, {"Quest Items"}),
    "Key Fragment 2": WOLItemData(432, ItemClassification.progression, {"Quest Items"}),
    "Key Fragment 3": WOLItemData(433, ItemClassification.progression, {"Quest Items"}),
    "Key To P.O. Box 114": WOLItemData(434, ItemClassification.progression, {"Quest Items"}),
    "Key To P.O. Box 441": WOLItemData(435, ItemClassification.progression, {"Quest Items"}),
    "Key-Shaped El Vibrato Device": WOLItemData(436, ItemClassification.progression, {"Quest Items"}),
    "Left Half Of Curly's Map": WOLItemData(437, ItemClassification.progression, {"Quest Items"}),
    "Letter To Roy Bean": WOLItemData(438, ItemClassification.useful, {"Quest Items"}),
    "Lime Lime Jellybeans": WOLItemData(439, ItemClassification.useful, {"Quest Items"}),
    "List Of Buffalo Bones": WOLItemData(440, ItemClassification.progression, {"Quest Items"}),
    "Lucky Cap": WOLItemData(441, ItemClassification.progression, {"Quest Items"}),
    "Marching Orders": WOLItemData(442, ItemClassification.useful, {"Quest Items"}),
    "Mary Stearns' Diary": WOLItemData(443, ItemClassification.filler, {"Quest Items"}),
    "Mint Mint Jellybeans": WOLItemData(444, ItemClassification.useful, {"Quest Items"}),
    "Mrs. Gun's Blueprint": WOLItemData(445, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "Mule Rental Contract": WOLItemData(446, ItemClassification.useful, {"Quest Items"}),
    "Mushroom Map": WOLItemData(447, ItemClassification.useful, {"Quest Items"}),
    "Mushroom Plucking Pliers": WOLItemData(448, ItemClassification.progression, {"Quest Items"}),
    "Nearly-Empty Herbicide Can": WOLItemData(449, ItemClassification.filler, {"Quest Items"}, is_dlc=True),
    "Overdue Breadwood Book": WOLItemData(450, ItemClassification.progression, {"Quest Items"}),
    "Owl Camera": WOLItemData(451, ItemClassification.useful, {"Quest Items"}),
    "Packrat Skeleton": WOLItemData(452, ItemClassification.useful, {"Quest Items"}),
    "Paper Bag": WOLItemData(453, ItemClassification.useful, {"Quest Items"}),
    "Passenger Car Key": WOLItemData(454, ItemClassification.useful, {"Quest Items"}),
    "Photo Of L'ardest": WOLItemData(455, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "Picture Of Mary Stearns": WOLItemData(456, ItemClassification.useful, {"Quest Items"}),
    "Plaid Skirt": WOLItemData(457, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "Pope's Pelvis": WOLItemData(458, ItemClassification.progression, {"Quest Items"}),
    "Postal Code Sheet": WOLItemData(459, ItemClassification.progression, {"Quest Items"}),
    "Purple Grass": WOLItemData(460, ItemClassification.useful, {"Quest Items"}),
    "Pvt. Lemmon's Diary": WOLItemData(461, ItemClassification.filler, {"Quest Items"}),
    "Pvt. Matthau's Diary": WOLItemData(462, ItemClassification.filler, {"Quest Items"}),
    "Recovered Mug": WOLItemData(463, ItemClassification.useful, {"Quest Items"}),
    "Remains Of The Potemkin Gang": WOLItemData(464, ItemClassification.progression, {"Quest Items"}),
    "Right Half Of Curly's Map": WOLItemData(465, ItemClassification.progression, {"Quest Items"}),
    "Robe Receipt": WOLItemData(466, ItemClassification.progression, {"Quest Items"}),
    "Santa Cortada's Skull": WOLItemData(467, ItemClassification.progression, {"Quest Items"}),
    "Sauté Knife": WOLItemData(468, ItemClassification.progression, {"Quest Items"}),
    "Shaker Of Saltpeter": WOLItemData(469, ItemClassification.progression, {"Quest Items"}),
    "Sharpened Ghost Pencil": WOLItemData(470, ItemClassification.progression, {"Quest Items"}),
    "Shaving Cream Pie": WOLItemData(471, ItemClassification.useful, {"Quest Items"}),
    "Shower Curtain": WOLItemData(472, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "Silver-Plated Barbed Wire": WOLItemData(473, ItemClassification.progression, {"Quest Items"}),
    "Skull With An Odd Tag On It": WOLItemData(474, ItemClassification.useful, {"Quest Items"}),
    "Slide Whistle": WOLItemData(475, ItemClassification.progression, {"Quest Items"}),
    "Small Blowtorch": WOLItemData(476, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "Southeast-Western Murder Pepper": WOLItemData(477, ItemClassification.progression, {"Quest Items"}),
    "Spooky Lullaby Sheet Music": WOLItemData(478, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "St. Beefus' Finger": WOLItemData(479, ItemClassification.progression, {"Quest Items"}),
    "Sticky Note": WOLItemData(480, ItemClassification.progression, {"Quest Items"}),
    "Strange Stone Arrow": WOLItemData(481, ItemClassification.progression, {"Quest Items"}),
    "Syrup Tap": WOLItemData(482, ItemClassification.progression, {"Quest Items"}),
    "Tannery Back Door Key": WOLItemData(483, ItemClassification.progression, {"Quest Items"}),
    "Tannery St. Rage Key": WOLItemData(484, ItemClassification.progression, {"Quest Items"}),
    "Tea Service": WOLItemData(485, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "Tiny Stick Of Dynamite": WOLItemData(486, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "Toy Skeletons": WOLItemData(487, ItemClassification.progression, {"Quest Items"}),
    "Unstable Stick Of Dynamite": WOLItemData(488, ItemClassification.progression, {"Quest Items"}),
    "Very Thick Spectacles": WOLItemData(489, ItemClassification.useful, {"Quest Items"}),
    "Wad Of Stuffing": WOLItemData(490, ItemClassification.progression, {"Quest Items"}, is_dlc=True),
    "Weird Rock Sample": WOLItemData(491, ItemClassification.progression, {"Quest Items"}),
    "Whining El Vibrato Object": WOLItemData(492, ItemClassification.useful, {"Quest Items"}),
    "A Portable Alchemistry Set": WOLItemData(494, ItemClassification.useful, {"Miscellany"}),
    "A Portable Arcane Oven": WOLItemData(495, ItemClassification.useful, {"Miscellany"}),
    "A Portable Leatherwork Bench": WOLItemData(496, ItemClassification.useful, {"Miscellany"}),
    "All-Purpose Beans x2": WOLItemData(497, ItemClassification.useful, {"Miscellany"}),
    "Balloon": WOLItemData(498, ItemClassification.progression, {"Miscellany"}),
    "Bean-Iron Nugget": WOLItemData(499, ItemClassification.progression, {"Miscellany"}, 3),
    "Blank Postcard": WOLItemData(500, ItemClassification.progression, {"Miscellany"}, 5),
    "Bottle Of Buffalo Tranquilizers": WOLItemData(501, ItemClassification.useful, {"Miscellany"}),
    "Cool Sapphire": WOLItemData(502, ItemClassification.progression, {"Miscellany"}),
    "Cowseye": WOLItemData(503, ItemClassification.progression, {"Miscellany"}),
    "Delicate Bean-Iron Nugget": WOLItemData(504, ItemClassification.progression, {"Miscellany"}, 3),
    "Dense Bean-Iron Nugget": WOLItemData(505, ItemClassification.progression, {"Miscellany"}, 3),
    "Disturbing Portrait": WOLItemData(506, ItemClassification.useful, {"Miscellany"}),
    "Effluvious Emerald Ring": WOLItemData(507, ItemClassification.progression, {"Miscellany"}),
    "Elaborate Puzzle Box": WOLItemData(508, ItemClassification.useful, {"Miscellany"}),
    "Handful Of Old Coins": WOLItemData(509, ItemClassification.filler, {"Miscellany"}),
    "Hanky": WOLItemData(510, ItemClassification.filler, {"Miscellany"}),
    "Herbal Remedy": WOLItemData(511, ItemClassification.filler, {"Miscellany"}),
    "Infernal Soul Fragment": WOLItemData(512, ItemClassification.filler, {"Miscellany"}),
    "Jaw Harp": WOLItemData(513, ItemClassification.useful, {"Miscellany"}),
    "Miniature Piano": WOLItemData(514, ItemClassification.useful, {"Miscellany"}),
    "Personalized Gun Manor Shotglass": WOLItemData(515, ItemClassification.useful, {"Miscellany"}, is_dlc=True),
    "Pocketknife": WOLItemData(516, ItemClassification.filler, {"Miscellany"}),
    "Polished Diorite": WOLItemData(517, ItemClassification.progression, {"Miscellany"}),
    "Puzzle Cube": WOLItemData(518, ItemClassification.filler, {"Miscellany"}),
    "Shovel": WOLItemData(519, ItemClassification.progression, {"Miscellany"}),
    "Silenter": WOLItemData(520, ItemClassification.progression, {"Miscellany"}, is_dlc=True),
    "Strange Lamp": WOLItemData(522, ItemClassification.filler, {"Miscellany"}),
    "Strange Silvery Crystal": WOLItemData(523, ItemClassification.progression, {"Miscellany"}),
    "Superdense Coal": WOLItemData(524, ItemClassification.progression, {"Miscellany"}),
    "Unbreakable Ruby": WOLItemData(525, ItemClassification.progression, {"Miscellany"}),
    "Silver Nugget x5": WOLItemData(526, ItemClassification.filler, {"Miscellany"}),
    "Handful Of Nails x4": WOLItemData(527, ItemClassification.progression, {"Miscellany"}),
    "Stock Certificate x3": WOLItemData(528, ItemClassification.filler, {"Miscellany"}, 2),
    "Human Ashes x2": WOLItemData(529, ItemClassification.progression, {"Quest Items"}),
    "Cheap Wine x11": WOLItemData(530, ItemClassification.filler, {"Consumables", "Booze"}),
    "Sulphur Match x4": WOLItemData(531, ItemClassification.progression, {"Consumables", "Combat"}),
    "Military Medical Supplies": WOLItemData(532, ItemClassification.filler, {"Consumables", "Combat", "Booze"}),
    "Decent Booze": WOLItemData(533, ItemClassification.filler, {"Consumables", "Booze"}),
    "Cheap Booze": WOLItemData(534, ItemClassification.filler, {"Consumables", "Booze"}),
    "Lead Pie": WOLItemData(535, ItemClassification.filler, {"Consumables", "Food"}),
    "Drugs": WOLItemData(536, ItemClassification.filler, {"Consumables", "Combat", "Potions"}),
    "Goblin Sandwich x5": WOLItemData(537, ItemClassification.filler, {"Consumables", "Food"}),
    "Goblin Chicory x3": WOLItemData(538, ItemClassification.filler, {"Consumables", "Potions"}),
    "A Length Of Rope": WOLItemData(539, ItemClassification.progression, {"Miscellany"}),
    "Tainted Milk x3": WOLItemData(540, ItemClassification.filler, {"Consumables", "Potions"}),
    "Gold Tooth x3": WOLItemData(541, ItemClassification.progression, {"Miscellany"}),
    "Potted Meat x2": WOLItemData(542, ItemClassification.filler, {"Consumables", "Food"}),
    "Bottle Of Laudanum x6": WOLItemData(543, ItemClassification.filler, {"Consumables", "Potions"}),
    "Unrefined Meat Nugget x4": WOLItemData(544, ItemClassification.filler, {"Miscellany"}),
    "Bundle Of Bones": WOLItemData(545, ItemClassification.filler, {"Miscellany"}),
    "Ghost Pickle x3": WOLItemData(546, ItemClassification.filler, {"Consumables", "Food"}),
    "\"Cotton Candy\" x3": WOLItemData(547, ItemClassification.filler, {"Consumables", "Food"}),
    "Dynamite x5": WOLItemData(548, ItemClassification.filler, {"Consumables", "Combat"}),
    "Dynamite x10": WOLItemData(549, ItemClassification.filler, {"Consumables", "Combat"}),
    "Lasso x3": WOLItemData(550, ItemClassification.filler, {"Consumables", "Combat"}),
    "El Vibrato Fluid x5": WOLItemData(551, ItemClassification.useful, {"Miscellany"}),
    "Can Of Schmaltz Blue Ribbon x3": WOLItemData(552, ItemClassification.filler, {"Consumables", "Booze"}),
    "Sack Of Meat Nuggets": WOLItemData(553, ItemClassification.useful, {"Miscellany"}, 3),
    "Perfect Cup Of Coffee": WOLItemData(554, ItemClassification.filler, {"Consumables", "Potions"}),
    "El Vibrato Seltzer x3": WOLItemData(555, ItemClassification.filler, {"Consumables", "Potions"}),
    "Tripe Pie x2": WOLItemData(556, ItemClassification.filler, {"Consumables", "Food"}),
    "Decent Whiskey x2": WOLItemData(557, ItemClassification.filler, {"Consumables", "Booze"}),
    "Patent Emetic x5": WOLItemData(558, ItemClassification.filler, {"Consumables", "Combat"}),
    "Skull Chips x3": WOLItemData(559, ItemClassification.filler, {"Miscellany"}),
    "Handful Of Loose Teeth x3": WOLItemData(560, ItemClassification.filler, {"Miscellany"}),
    "Snake Chunks": WOLItemData(561, ItemClassification.useful, {"Consumables", "Combat"}),
    "El Vibrato Punchcard (Complicated) x5": WOLItemData(562, ItemClassification.filler, {"Quest Items"}, 2),
    "El Vibrato Punchcard x5": WOLItemData(563, ItemClassification.filler, {"Quest Items"}),
    "El Vibrato Scraps x10": WOLItemData(564, ItemClassification.filler, {"Quest Items"}),
    "El Vibrato Scraps x45": WOLItemData(565, ItemClassification.useful, {"Quest Items"}),
    "Skeleton Bone x4": WOLItemData(566, ItemClassification.filler, {"Miscellany"}),
    "Needle x5": WOLItemData(567, ItemClassification.progression, {"Miscellany"}, 2),
    "Jar Of Moonshine": WOLItemData(568, ItemClassification.filler, {"Consumables", "Booze"}),
    "Jar Of Peanut Butter x2": WOLItemData(569, ItemClassification.filler, {"Consumables", "Food"}),
    "Goat Steak x3": WOLItemData(570, ItemClassification.filler, {"Consumables", "Food"}),
    "Moon Bits x3": WOLItemData(571, ItemClassification.useful, {"Miscellany"}),
    "Fancy Coffee": WOLItemData(572, ItemClassification.filler, {"Consumables", "Potions"}),
    "Spider Pie x2": WOLItemData(573, ItemClassification.filler, {"Consumables", "Food"}, is_dlc=True),
    "Box Of Science Doohickeys": WOLItemData(574, ItemClassification.useful, {"Quest Items"}, 4, is_dlc=True),
    "Tinned Caviar x3": WOLItemData(575, ItemClassification.filler, {"Consumables", "Food"}, is_dlc=True),
    "Old-Timey Ointment x3": WOLItemData(576, ItemClassification.filler, {"Consumables", "Potions"}, is_dlc=True)
}

item_name_to_id: Dict[str, int] = {name: base_id + data.id_offset for name, data in item_table.items()}