from typing import Dict, Set

#Note: Access paths do not always correlate to the in-game map regions
#Some map regions (e.g. C) have multiple possible initial access points that need to link back to the region for wandering
#Without map/entrance rando, many of these could be condensed into larger groups
region_table: Dict[str, Set[str]] = {
    "Menu": {"Your Family's Farm"},
    "Your Family's Farm": {"Dirtwater"},
    "Dirtwater": {"Map Region A", "Railroad Camp (East)", "Desert House", "Cavern Canyon", "The Potemkin Gang",
                  "Old Millinery", "Abandoned Pickle Factory", "The Daveyard", "Fort Cowardice",
                  "The Perfessor's House", "Rescue Mission", "Tony's Boots", "Murray's Curiosity & Bean",
                  "Grady's Fine Leather Goods", "Alexandria's Bookstore", "Fort Alldead", "Gun Manor"
                  "Miscellaneous"},
    "Map Region A": {"Shaggy Dog Cave", "Silversmith's House", "Stearns Ranch", "Snakepit Mine", "The Daveyard",
                     "Buttonwillow's Store", "Fort Cowardice", "Wanderin' Sally's Camp", "Random Encounters A"},
    "Railroad Camp (East)": {"Map Region B", "Gustavson Gulch", "Buttonwillow's Store", "Railroad Camp (West)"},
    "Silversmith's House": {"The Silver Plater"},
    "The Perfessor's House": {"Lost Dutch Oven Mine"},
    "Map Region B": {"Butterfield Ranch", "Kole Ridge Mine", "Dynamite Dan's", "Snake Spring", "Old Mission",
                     "Destroyed Campsite", "The Big Apple", "Random Encounters B"},
    "Butterfield Ranch": {"Kole Ridge Mine"},
    "Destroyed Campsite": {"Clown Campsite"},
    "Clown Campsite": {"Circus", "Danny's Tannery"},
    "Map Region C": {"Rescue Mission", "Fort Alldead", "Lazy-A Dude Ranch", "Humming Cave", "Circus",
                     "Random Encounters C"},
    "The Potemkin Gang": {"Map Region C"},
    "Old Millinery": {"Map Region C"},
    "Abandoned Picle Factory": {"Map Region C"},
    "The Silver Plater": {"Map Region C"},
    "Lost Dutch Oven Mine": {"Map Region C"},
    "Rescue Mission": {"Map Region C", "Humming Cave"},
    "Fort Alldead": {"Map Region C"},
    "Lazy-A Dude Ranch": {"Map Region C"},
    "Circus": {"Map Region C", "Circus (Inside)"},
    "Circus (Inside)": {"Danny's Tannery"},
    "Railroad Camp (West)": {"Map Region E", "Breadwood", "Roy Bean's House", "Necromancer's Tower", "Frisco"},
    "Breadwood": {"Map Region D", "Ghostwood", "Postal Way Station", "Soupstock Lode", "Ol' Schmaltz Brewery",
                  "Baker Boys' Hideout", "Military Cemetery", "Alexandria Ranch", "Petting Cemetery"},
    "Map Region D": {"Alexandria Ranch", "Curious Abandoned Well", "Curious Copse", "Fort Treason", "Ghostwood",
                     "Jumbleneck Mine", "Military Cemetery", "Random Encounters D"},
    "Jumbleneck Mine": {"Jumbleneck Mine (Inside)"},
    "Curious Abandoned Well": {"Curious Abandoned Well Facility"},
    "Postal Way Station": {"Chuck's House", "Reboot Hill"},
    "Military Cemetery": {"Fort Memoriam"},
    "Alexandria Ranch": {"Fort Treason", "Alexandria Ranch Vault"},
    "Map Region E": {"Reboot Hill", "Hellstrom Ranch", "Fort Memoriam", "Soupstock Lode", "The West Pole",
                     "The Great Garbanzo's Hideout", "The Old Medicine Show", "Random Encounters E"},
    "Reboot Hill": {"Hellstrom Ranch"},
    "Roy Bean's House": {"Map Region F", "Jelly Bean Thieves' Hideout", "Ol' Granddad", "Shroomcave"},
    "Map Region F": {"Buffalo Pile", "Petting Cemetery", "Kellogg Ranch", "Madness Maw Mine",
                     "Roy Bean's House", "Fort of Darkness", "Random Encounters F"},
    "Petting Cemetery": {"Buffalo Pile", "Fort of Darkness", "Kellogg Ranch"},
    "Madness Maw Mine": {"El Vibrato Outpost (MMM)"},
    "Frisco": {"Map Region G", "Wasco's Comedy Shack", "Roy Bean's House", "Dr. Morton's House"},
    "Map Region G": {"Abandoned Mine", "Fort Unnecessary", "Last Custard Stand", "Jeweler's Cabin",
                     "Random Encounters G"},
    "Abandoned Mine": {"Abandoned Mine (Inside)"},
    "Fort Unnecessary": {"Jeweler's Cabin", "Alamo Rent-A-Mule"},
    "Dr. Morton's House": {"Old Cave", "Abandoned Mine"},
    "Alamo Rent-A-Mule": {"Map Region H", "Deepest Delve Mine"},
    "Map Region H": {"Alamo Rent-A-Mule", "Curious False Mountain", "Curious Flat Plain", "Deepest Delve Mine",
                     "Halloway's Hideaway", "Moonshine Still", "Olive Garden's Homestead", "Random Encounters H"},
    "Deepest Delve Mine": {"Deepest Delve Mine (Elevator Fixed)"},
    "Miscellaneous": {"Leatherworkery Crafting", "Master Cookery Crafting", "Progressive Containers"},
    "Gun Manor": {"Gun Manor Hedge Maze", "Gun Manor Carriage House", "Gun Manor Visitor Center",
                  "Gun Manor First Floor"},
    "Gun Manor Hedge Maze": {"Gun Manor Cellar"},
    "Gun Manor Cellar": {"Gun Manor Laboratory"},
    "Gun Manor First Floor": {"Gun Manor Cellar", "Gun Manor Parlor", "Gun Manor Kitchen", "Gun Manor Dining Room",
                              "Gun Manor Second Floor"},
    "Gun Manor Kitchen": {"Gun Manor Larder", "Gun Manor Pantry"},
    "Gun Manor Second Floor": {"Gun Manor Library", "Gun Manor Art Gallery", "Gun Manor Restroom",
                               "Gun Manor Guest Rooms", "Gun Manor Third Floor"},
    "Gun Manor Third Floor": {"Mr. Gun's Manliness Room", "Mrs. Gun's Room", "Gun Manor Music Room",
                              "Gun Manor Children's Quarters"},
    "Mr. Gun's Manliness Room": {"Gun Manor Billiards Room", "Mr. Gun's Bowling Room", "Mr. Gun's Trophy Room"},
    "Gun Manor Billiards Room": {"Gun Manor Belfry"},
    "Gun Manor Children's Quarters": {"Gun Manor Nursery", "Gun Manor Toddler's Room", "Gun Manor Tween Room"}
}